name: Deploy

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install deps
      run: |
        sudo apt-get install python3-setuptools
        sudo pip3 install mkdocs mkdocs-bootswatch
        
    - name: Deploy MkDocs
      run: |
        mkdocs build
        mkdocs gh-deploy -b site
